### ISSUE TITLE
Remove sitemap. Keep dependencies minimized.

### ISSUE THREAD

**Issue by rassol** [johnotander/pixyll#121]
I just now pulled the master branch and ran `jekyll serve` locally.

I get this:

```
in `require': cannot load such file -- jekyll-sitemap (LoadError)
```

When commenting out the requirement in the config everything works directly.

Unless Pixyll is designed specifically for GitHub pages I think you should remove
jekyll-sitemap (I am guessing this gem is installed on github pages).

If you want to add more features that are designed to work out of the box with github pages why not do it on another branch and keep the Pixyll core clean and as simple as possible on master branch.

I rather we keep it as simple as possible to use Pixyll, minimizing install requirements. That is why I am using Jekyll in the first place, to get rid of the complexity with databases etc. To be able to just download the latest Pixyll to an empty folder and run Jekyll Serve is great. No gemfile or anything.

Pixyll is great now that it is so simple. I hope that we can keep this in mind as development continues and hopefully not add anymore dependencies.

**Comment by johnotander** [comment]
Hey @rassol,

I definitely see where you are coming from here. Pixyll is intended to be simple. Super simple. The introduction of `jekyll-sitemap` into the `_config.yml` makes it a bit less so. I'm thinking a way to solve this problem is to comment out the gems section into something like:

```yml
# For sitemaps, which are compatible with Github Pages, uncomment out the following two lines.
# Note that you will need to then install the jekyll-sitemap gem to run this project locally with `gem install jekyll-sitemap`
# gems:
#  - jekyll-sitemap
```

That way, it's still pretty simple to integrate sitemaps, while still _only_ requiring the following steps to get up and running with Pixyll:

```
gem install jekyll
jekyll serve
```

I'd initially merged in the PR for this because I assumed that `jekyll-sitemap` was an included dependency for the `jekyll` gem. Unbeknownst to me, I just had the gem installed already from another project. The current dependencies for Jekyll:

```
fast-stemmer, classifier-reborn, ffi, rb-inotify, rb-fsevent, hitimes, timers, celluloid, listen, jekyll-watch, sass, jekyll-sass-converter, coffee-script-source, execjs, coffee-script, jekyll-coffeescript, jekyll-gist, jekyll-paginate, blankslate, parslet, toml, redcarpet, yajl-ruby, posix-spawn, pygments.rb, colorator, safe_yaml, mercenary, kramdown, liquid, jekyll
```

Thanks for pointing out this inconvenience. When I get a moment I will submit a PR with an update to require an opt-in for sitemaps.

**Comment by rassol** [comment]
Your solution is not scalable as more gems find their way in. Messy config.

The jekyll `build` and `serve` options accept a `--config` parameter that takes a comma separated list of config files, where later ones override former. In this case, another solution would be to have a config _config-github.yml and put extra stuff in there.
Oh wait, that probably doesn't work with GitHub pages since you are not building yourself. Nevermind :)

Maybe there's some other solutions. Having another branch for github version is messy too but if additional files are added to support some new dependency that are not needed in the base configuration of Pixyll, I do not think it should be in the same branch.

I only know Ruby to the extent that I can install and use Jekyll. So I think that all gems that come with Jekyll are fine. Just running the 2 lines you mentioned to get it running is super great. If the sitemap gem were to be included in Jekyll I would have no problem with this since there are no extra steps.

Anyway, I think your solution works for now but not in the long run.

**Comment by johnotander** [comment]
I don't really foresee more than another gem or two being added down the road (if that), so I don't think a few commented out lines will be too disastrous. I think this is preferable to maintaining a separate branch, and since a new user needs to modify the config anyway, they can either: remove the commented out gems list, uncomment it and install the gem, or just leave it. Seems simple enough to me.

Yeah, the problem with the config option is, as part of the ease of use, I'd like for Pixyll to be 100% Github Pages compatible. At this current time, Github Pages doesn't allow you to pass any build options.

For the time being we can roll with the commented out list, and consider new options if that list grows to more than one or two.

Thanks for your thoughts, and I appreciate you taking the time to open this issue. I think this proposed solution will definitely be an improvement to what was there before!

**Comment by rassol** [comment]
Really, ok. 
2 or 3 is no problem, but yes, if it grows to more than that...

Thank you too!

**Comment by bennettrogers** [comment]
FYI, this still happens when serving from the current master branch. I'm not sure if the intention was to leave it as-is or to go with the opt-in approach for the list of gems, but from reading this discussion it sounds like the issue might have been forgotten once the issue was closed.

Thanks!

**Comment by johnotander** [comment]
Good catch, I'll get that fixed right now. Thanks!
