### ISSUE TITLE
Stretch image in mobile version

### ISSUE THREAD

**Issue by marste** [johnotander/pixyll#122]
If you view pictures in the mobile version, they do not maintain the proportions.

**Comment by johnotander** [comment]
Thanks for reporting this, @marste! A few questions to help diagnosing:

What device/browser/version?
Do you have an example pushed anywhere I can look at?

**Comment by marste** [comment]
My device is Samsung Galaxy SII i9100 with any browser.
This is an example: http://tech.marzorati.co/rifugio-san-tomaso-580-m-valmadrera-lc/

Thanks John!

**Comment by johnotander** [comment]
Great, thanks for the info. After a bit of digging, it looks like the reason the images have distorted proportions on mobile is a combination of two things:

Pixyll sets the `max-width` to `100%` for all image elements, while the image markdown specifies the height and width through attributes:

```md
[<img src="http://res.cloudinary.com/marzorati-co/image/upload/v1408107877/san_tomaso_ujh02o.png" alt="san_tomaso" width="450" height="600" class="alignleft size-full wp-image-2595" />][1]
```

Removing the `height` and `width` attributes, like so:

```md
[<img src="http://res.cloudinary.com/marzorati-co/image/upload/v1408107877/san_tomaso_ujh02o.png" alt="san_tomaso" class="alignleft size-full wp-image-2595" />][1]
```

Will result in:

![kchco1audriwnw-32uke3kzrc8tixp8lscwu4uqbcdg](https://cloud.githubusercontent.com/assets/1424573/5865277/8197b842-a245-11e4-8ff2-da77837fb2f8.png)

With the following mobile view:

![11rropfuf15be53tgkvdudszibo5vep4jc8imrai5zs](https://cloud.githubusercontent.com/assets/1424573/5865285/8a892120-a245-11e4-8af7-18b8654e6f3a.png)

I'm not sure if that's exactly the sizing you want, but that will begin to put you on the right track.

For some reason, which was surprising to me, the `img` styling in`pixyll.css` was overriding the inline `width` attribute, causing the image to distort since the `height` is still fixed.

Devtools CSS:

```css
mg {
  width: auto;
  max-width: 100%;
}

img[Attributes Style] {
  width: 450px; /* Overridden */
  height: 600px;
}
```

This was rather surprising since I was under the impression that `!important` was required in CSS to override inline styles. Beats me?

Hopefully this helps @marste

**Comment by marste** [comment]
Thank you John!
The url was added automatically by a wordpress plugin and migrating posts remained with those parameters.
