### ISSUE TITLE
No tags on posts?

### ISSUE THREAD

**Issue by Joshfindit** [johnotander/pixyll#165]
Specifying the post tags with frontmatter does not seem to do anything.

**Comment by Malayke** [comment]
@Joshfindit yes, no tags and categories, if pixyll provide those, I want to use this theme

**Comment by aohorodnyk** [comment]
@johnotander Thanks very much, you created the best and simple theme, I like it.

@Joshfindit I implemented tags in this theme, because I want use tags and archive page, you can see it in https://github.com/aohorodnyk/articles but I didn't add javascript for showing only one tag posts when you select some theme... It's I will do when I will time for that.

Now I have minimalistic theme with all functionality which I need.

**Comment by johnotander** [comment]
Pixyll doesn't currently have any plans to support tagging, I'd recommend running with @aohorodnyk's fork if you'd like to incorporate that functionality. I've opted to avoid tagging because true tag functionality (from what I can understand) requires either a plugin or javascript, both of which I'd like to avoid in the base version of this theme.
