### ISSUE TITLE
Jekyll 3: Pagination Generator

### ISSUE THREAD

**Issue by keenam** [johnotander/pixyll#224]
Hello,

I am adopting the newly released final version of Jekyll 3.0 and see that there is no more built-in pagination and https://github.com/jekyll/jekyll-paginate is retired.

Some suggest in the talk at:
https://talk.jekyllrb.com/t/announcement-retiring-jekyll-paginate/1004/14

to switch to:
https://github.com/octopress/paginate

What are your thoughts on this?

**Comment by johnotander** [comment]
Whoa. Thanks for bringing this to my attention. I was definitely unaware.

IMO this is rather unfortunate. This means that pagination will be lost for vanilla Jekyll installs and standard Github Pages deployment if the functionality isn't added to the `jekyll` or `github-pages` gem. Which likely means pagination will be removed from Pixyll if it is no longer supported. With base Pixyll I intend on targeting Github Pages to ensure installation and deployment is as simple as possible.

##### Why I only want to support vanilla Jekyll and Github Pages

One of the key features of Pixyll is its simplicity and ease of deployment to Github Pages. It only has one dependency, the `jekyll` gem. No Gemfile. No bundle installs. This makes it easy for users to get up and running, and deployed automagically by `github-pages` simply by pushing to Github. My understanding is that Github Pages only supports a handful of gems as part of their automatic build process:

```
$ github-pages versions
+-----------------------+---------+
| Gem                   | Version |
+-----------------------+---------+
| jekyll                | 2.4.0   |
| jekyll-coffeescript   | 1.0.1   |
| jekyll-sass-converter | 1.3.0   |
| kramdown              | 1.5.0   |
| maruku                | 0.7.0   |
| rdiscount             | 2.1.7   |
| redcarpet             | 3.3.2   |
| RedCloth              | 4.2.9   |
| liquid                | 2.6.2   |
| pygments.rb           | 0.6.3   |
| jemoji                | 0.5.0   |
| jekyll-mentions       | 0.2.1   |
| jekyll-redirect-from  | 0.8.0   |
| jekyll-sitemap        | 0.8.1   |
| jekyll-feed           | 0.3.1   |
+-----------------------+---------+
```

Using an Octopress plugin will require additional complexity if it isn't integrated with `jekyll` itself. Though, I hope they do in fact do that. It would make sense to me if they replaced `jekyll-paginate` with `octopress-paginate` and end users can continue using Jekyll pagination without ever knowing, the external API remaining intact and functional.

From what I can tell, and please correct me if I'm wrong (I usually am :smile:), Octopress pagination isn't supported by Github Pages. This would then require a [build](https://github.com/octopress/octopress) step for Github Pages or a [deployment](https://github.com/octopress/deploy) step for other platforms.

So, it looks like, unless `jekyll` or `github-pages` add `octopress-pagination`, I won't be able to support it. However, we can still leave in the pagination styling and html partials so that those that want to customize the theme and their jekyll/deployment configurations have the ability to do so.

¯\\_(ツ)_/¯

**Comment by jtremback** [comment]
If I'm not mistaken, it looks like they added it?

https://github.com/irfanfadilah/pages-gem/commit/31c01d900a12f29aca40d9a61e6faf4560fbe2d8

**Comment by alxmjo** [comment]
In the mean time, what's the best way to allow for pagination of Pixyll? I'm currently getting this error on a local install:

---
Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
---

**Comment by johnotander** [comment]
@alxmjo I _believe_ that you can add the following to your `_config.yml`:

```yml
gems:
  - jekyll-paginate
```

If that doesn't work let me know and I'll do some digging : )

**Comment by alxmjo** [comment]
That appears to do the trick. Thanks!

**Comment by johnotander** [comment]
I've decided to go the route of using the `github-pages` gem, and requiring `bundler` for a standard install. After some thinking, I believe that it is the simplest way to perform the installation process and adds niceties like site maps and pagination back.

**Comment by jtremback** [comment]
This will still work with gh-pages without a preprocessing step on my computer?

**Comment by johnotander** [comment]
@jtremback correct, assuming you've installed `bundler` (`$ gem install bundler`) and run `$ bundle install`.

**Comment by sbfp** [comment]
Hello, 
I'm currently trying to get Pixyll up and running locally with jekyll. But I can't seem go get i working even with the workarounds mentioned above.

I've installed bundler, jekyll-pagination and just recently cloned the Pixyll project - but I still get the following error, when starting `jekyll serve`
