### ISSUE TITLE
Why are files like the Gemfile published to _site?

### ISSUE THREAD

**Issue by VictorioBerra** [johnotander/pixyll#303]
Just curious. I am using a tool called s3_website to deploy my site and i noticed a bunch of stuff in my bucket that didn't need to be there so I double checked and sure enough the _site directory has things like the Gemfile in it. Why arent these excluded by default?

**Comment by bartekpl** [comment]
Can't say for sure but my best guess is that's because these files vary depending on each user. For example my `exclude:` list contains additional files not included in initial `jekyll new my-awesome-site` or in vanilla pixyll. I'm using a script during build process, some files are a result of jekyll plugins (like `tweet-cache`) and so forth.
